[package]
name = "feline-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "feline_core"
crate-type = ["lib", "staticlib"]

[[bin]]
name = "uniffi-bindgen-feline"
path = "uniffi-bindgen.rs"
required-features = ["ffi"]

[features]
default = []
ffi = ["dep:uniffi", "vpn"]
vpn = ["dep:base64", "dep:boringtun", "dep:rand", "dep:smoltcp"]

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "time", "net", "io-util", "fs"] }
futures-util = { workspace = true }
wreq = { workspace = true }
wreq-util = { workspace = true }
url = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
governor = { workspace = true }
tracing = { workspace = true }
uniffi = { version = "0.32.0", features = ["tokio", "cli"], optional = true }
boringtun = { workspace = true, optional = true }
smoltcp = { workspace = true, optional = true }
base64 = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
md-5 = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
