export global Theme {
    out property <color> bg: #141218;
    out property <color> surface: #1d1b20;
    out property <color> surface-container: #222027;
    out property <color> surface-container-high: #2b2930;
    out property <color> outline-variant: #49454f;
    out property <color> primary: #a8c7fa;
    out property <color> primary-container: #28438e;
    out property <color> on-primary: #062e6f;
    out property <color> text: #e6e0e9;
    out property <color> text-muted: #cac4d0;
    out property <color> success: #86db98;
    out property <color> warn: #ffd075;
    out property <color> danger: #ffb4ab;
    out property <color> extreme: #0e0c12;
}
